server:
  port: 9999
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:xjUFioNKfAczwXdrITBkWiXOlXjZaCrY@centerbeam.proxy.rlwy.net:51416/railway
    username: root
    password: 12345678
    hikari:
      connectionTimeout: 30000
      minimumIdle: 12
      maximumPoolSize: 50
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      leakDetectionThreshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_updates: true

jwt:
  secret: C2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OHC2H5OH
  expiration: 28800 # 8 hours